





CREATE TABLE Contract (

 primaryKey UUID NOT NULL,

 is_signed BOOLEAN NULL,

 conract_name VARCHAR(255) NULL,

 conract_user INT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Teacher (

 primaryKey UUID NOT NULL,

 status VARCHAR(255) NULL,

 user_name VARCHAR(255) NULL,

 user_sname VARCHAR(255) NULL,

 user_lname VARCHAR(255) NULL,

 user_login VARCHAR(255) NULL,

 user_password VARCHAR(255) NULL,

 user_email VARCHAR(255) NULL,

 user_reg_date TIMESTAMP(3) NULL,

 user_role INT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Student (

 primaryKey UUID NOT NULL,

 selected_course INT NULL,

 current_marks INT NULL,

 avg_mark INT NULL,

 user_name VARCHAR(255) NULL,

 user_sname VARCHAR(255) NULL,

 user_lname VARCHAR(255) NULL,

 user_login VARCHAR(255) NULL,

 user_password VARCHAR(255) NULL,

 user_email VARCHAR(255) NULL,

 user_reg_date TIMESTAMP(3) NULL,

 user_role INT NULL,

 Contract UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Mark (

 primaryKey UUID NOT NULL,

 mark INT NULL,

 mark_date TIMESTAMP(3) NULL,

 mark_student INT NULL,

 mark_course INT NULL,

 Course UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Course (

 primaryKey UUID NOT NULL,

 course_name VARCHAR(255) NULL,

 course_begin_time TIMESTAMP(3) NULL,

 course_end_time TIMESTAMP(3) NULL,

 Student UUID NOT NULL,

 Semester UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Semester (

 primaryKey UUID NOT NULL,

 start TIMESTAMP(3) NULL,

 "end" TIMESTAMP(3) NULL,

 semester_name VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Administrator (

 primaryKey UUID NOT NULL,

 status VARCHAR(255) NULL,

 user_name VARCHAR(255) NULL,

 user_sname VARCHAR(255) NULL,

 user_lname VARCHAR(255) NULL,

 user_login VARCHAR(255) NULL,

 user_password VARCHAR(255) NULL,

 user_email VARCHAR(255) NULL,

 user_reg_date TIMESTAMP(3) NULL,

 user_role INT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE "User" (

 primaryKey UUID NOT NULL,

 user_name VARCHAR(255) NULL,

 user_sname VARCHAR(255) NULL,

 user_lname VARCHAR(255) NULL,

 user_login VARCHAR(255) NULL,

 user_password VARCHAR(255) NULL,

 user_email VARCHAR(255) NULL,

 user_reg_date TIMESTAMP(3) NULL,

 user_role INT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (

 LockKey VARCHAR(300) NOT NULL,

 UserName VARCHAR(300) NOT NULL,

 LockDate TIMESTAMP(3) NULL,

 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (

 primaryKey UUID NOT NULL,

 Module VARCHAR(1000) NULL,

 Name VARCHAR(255) NULL,

 Value TEXT NULL,

 "User" VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (

 primaryKey UUID NOT NULL,

 "User" VARCHAR(255) NULL,

 Published BOOLEAN NULL,

 Module VARCHAR(255) NULL,

 Name VARCHAR(255) NULL,

 Value TEXT NULL,

 HotKeyData INT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (

 primaryKey UUID NOT NULL,

 Name VARCHAR(255) NOT NULL,

 DataObjectView VARCHAR(255) NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (

 primaryKey UUID NOT NULL,

 Name VARCHAR(255) NOT NULL,

 "Order" INT NOT NULL,

 PresentView VARCHAR(255) NOT NULL,

 DetailedView VARCHAR(255) NOT NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (

 primaryKey UUID NOT NULL,

 Caption VARCHAR(255) NOT NULL,

 DataObjectView VARCHAR(255) NOT NULL,

 ConnectMasterProp VARCHAR(255) NOT NULL,

 OwnerConnectProp VARCHAR(255) NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (

 primaryKey UUID NOT NULL,

 DataObjectType VARCHAR(255) NOT NULL,

 Container VARCHAR(255) NULL,

 ContainerTag VARCHAR(255) NULL,

 FieldsToView VARCHAR(255) NULL,

 FilterSetting_m0 UUID NOT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (

 primaryKey UUID NOT NULL,

 AppName VARCHAR(256) NULL,

 UserName VARCHAR(512) NULL,

 UserGuid UUID NULL,

 ModuleName VARCHAR(1024) NULL,

 ModuleGuid UUID NULL,

 SettName VARCHAR(256) NULL,

 SettGuid UUID NULL,

 SettLastAccessTime TIMESTAMP(3) NULL,

 StrVal VARCHAR(256) NULL,

 TxtVal TEXT NULL,

 IntVal INT NULL,

 BoolVal BOOLEAN NULL,

 GuidVal UUID NULL,

 DecimalVal DECIMAL(20,10) NULL,

 DateTimeVal TIMESTAMP(3) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (

 primaryKey UUID NOT NULL,

 Category VARCHAR(64) NULL,

 EventId INT NULL,

 Priority INT NULL,

 Severity VARCHAR(32) NULL,

 Title VARCHAR(256) NULL,

 Timestamp TIMESTAMP(3) NULL,

 MachineName VARCHAR(32) NULL,

 AppDomainName VARCHAR(512) NULL,

 ProcessId VARCHAR(256) NULL,

 ProcessName VARCHAR(512) NULL,

 ThreadName VARCHAR(512) NULL,

 Win32ThreadId VARCHAR(128) NULL,

 Message VARCHAR(2500) NULL,

 FormattedMessage TEXT NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAG (

 primaryKey UUID NOT NULL,

 Name VARCHAR(80) NOT NULL,

 Login VARCHAR(50) NULL,

 Pwd VARCHAR(50) NULL,

 IsUser BOOLEAN NOT NULL,

 IsGroup BOOLEAN NOT NULL,

 IsRole BOOLEAN NOT NULL,

 ConnString VARCHAR(255) NULL,

 Enabled BOOLEAN NULL,

 Email VARCHAR(80) NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMLG (

 primaryKey UUID NOT NULL,

 Group_m0 UUID NOT NULL,

 User_m0 UUID NOT NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMI (

 primaryKey UUID NOT NULL,

 User_m0 UUID NOT NULL,

 Agent_m0 UUID NOT NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE Session (

 primaryKey UUID NOT NULL,

 UserKey UUID NULL,

 StartedAt TIMESTAMP(3) NULL,

 LastAccess TIMESTAMP(3) NULL,

 Closed BOOLEAN NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMS (

 primaryKey UUID NOT NULL,

 Name VARCHAR(100) NOT NULL,

 Type VARCHAR(100) NULL,

 IsAttribute BOOLEAN NOT NULL,

 IsOperation BOOLEAN NOT NULL,

 IsView BOOLEAN NOT NULL,

 IsClass BOOLEAN NOT NULL,

 SharedOper BOOLEAN NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMP (

 primaryKey UUID NOT NULL,

 Subject_m0 UUID NOT NULL,

 Agent_m0 UUID NOT NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMF (

 primaryKey UUID NOT NULL,

 FilterText TEXT NULL,

 Name VARCHAR(255) NULL,

 FilterTypeNView VARCHAR(255) NULL,

 Subject_m0 UUID NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAC (

 primaryKey UUID NOT NULL,

 TypeAccess VARCHAR(7) NULL,

 Filter_m0 UUID NULL,

 Permition_m0 UUID NOT NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMLO (

 primaryKey UUID NOT NULL,

 Class_m0 UUID NOT NULL,

 Operation_m0 UUID NOT NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMLA (

 primaryKey UUID NOT NULL,

 View_m0 UUID NOT NULL,

 Attribute_m0 UUID NOT NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMLV (

 primaryKey UUID NOT NULL,

 Class_m0 UUID NOT NULL,

 View_m0 UUID NOT NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));


CREATE TABLE STORMLR (

 primaryKey UUID NOT NULL,

 StartDate TIMESTAMP(3) NULL,

 EndDate TIMESTAMP(3) NULL,

 Agent_m0 UUID NOT NULL,

 Role_m0 UUID NOT NULL,

 CreateTime TIMESTAMP(3) NULL,

 Creator VARCHAR(255) NULL,

 EditTime TIMESTAMP(3) NULL,

 Editor VARCHAR(255) NULL,

 PRIMARY KEY (primaryKey));




 ALTER TABLE Student ADD CONSTRAINT FK97c228392b4d4f2cb98f1e1b7dbcb94c FOREIGN KEY (Contract) REFERENCES Contract; 
CREATE INDEX Index32f9b5d1854548c9a6ef2f46aaf6a399 on Student (Contract); 

 ALTER TABLE Mark ADD CONSTRAINT FK17c9cea01a8a465195afe5311014af67 FOREIGN KEY (Course) REFERENCES Course; 
CREATE INDEX Index27294e360746466f8e3cb00e1ac3bce9 on Mark (Course); 

 ALTER TABLE Course ADD CONSTRAINT FK2c81e78b22ed4567b0e2d777f4cfa1d0 FOREIGN KEY (Student) REFERENCES Student; 
CREATE INDEX Index147c8414fd1c491b813d35b522a81aa5 on Course (Student); 

 ALTER TABLE Course ADD CONSTRAINT FK445c84c91ac34688bcb913ef19b005b9 FOREIGN KEY (Semester) REFERENCES Semester; 
CREATE INDEX Index9d855970494544c9a74f030e632e7c12 on Course (Semester); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FK9c2b6fbb004948c3918d7da89a816b98 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FKb5f66d9ae35943d391a624fd580cbbfd FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FK609aaa90f8174e9a9e420af8577ff2a7 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMLG ADD CONSTRAINT FK5eae1ae79abc4f80924cf9fcf1b74689 FOREIGN KEY (Group_m0) REFERENCES STORMAG; 

 ALTER TABLE STORMLG ADD CONSTRAINT FK0136cd4d7b9f4293ab4c6cba181b71b8 FOREIGN KEY (User_m0) REFERENCES STORMAG; 

 ALTER TABLE STORMI ADD CONSTRAINT FK886757121ef44487a2aeefb75e43e7f2 FOREIGN KEY (User_m0) REFERENCES STORMAG; 

 ALTER TABLE STORMI ADD CONSTRAINT FK42a914f9dbb0481b8702763875817f48 FOREIGN KEY (Agent_m0) REFERENCES STORMAG; 

 ALTER TABLE STORMP ADD CONSTRAINT FK3e306eb7dae14c7599cceb71d318074f FOREIGN KEY (Subject_m0) REFERENCES STORMS; 

 ALTER TABLE STORMP ADD CONSTRAINT FKdbda01c14da54d4197b4f73dd1417e22 FOREIGN KEY (Agent_m0) REFERENCES STORMAG; 

 ALTER TABLE STORMF ADD CONSTRAINT FK5a5431af640845d2a223058efd820226 FOREIGN KEY (Subject_m0) REFERENCES STORMS; 

 ALTER TABLE STORMAC ADD CONSTRAINT FKdfcf948387fb4d11bb0ed6dbe9d8c8f1 FOREIGN KEY (Filter_m0) REFERENCES STORMF; 

 ALTER TABLE STORMAC ADD CONSTRAINT FKd4f333242c4f4689bcafb251e13d56ab FOREIGN KEY (Permition_m0) REFERENCES STORMP; 

 ALTER TABLE STORMLO ADD CONSTRAINT FK8d1363b9c847405fb5719b9ecb8431da FOREIGN KEY (Class_m0) REFERENCES STORMS; 

 ALTER TABLE STORMLO ADD CONSTRAINT FKf1bc71bf9f81460199829c901a6db1a8 FOREIGN KEY (Operation_m0) REFERENCES STORMS; 

 ALTER TABLE STORMLA ADD CONSTRAINT FK1652421c9218491fb25dbce472ad8b86 FOREIGN KEY (View_m0) REFERENCES STORMS; 

 ALTER TABLE STORMLA ADD CONSTRAINT FKa1b2e0695d924511be386756cf4799aa FOREIGN KEY (Attribute_m0) REFERENCES STORMS; 

 ALTER TABLE STORMLV ADD CONSTRAINT FKb3e1d12dd6134882ae6c0c0a80020e20 FOREIGN KEY (Class_m0) REFERENCES STORMS; 

 ALTER TABLE STORMLV ADD CONSTRAINT FKaf01f62b95134d00a7ac1ea28cefb84f FOREIGN KEY (View_m0) REFERENCES STORMS; 

 ALTER TABLE STORMLR ADD CONSTRAINT FKf59fb459ad714774b09e60b54c62a96c FOREIGN KEY (Agent_m0) REFERENCES STORMAG; 

 ALTER TABLE STORMLR ADD CONSTRAINT FK88ae527d93c44007b9b67dfd505a8d88 FOREIGN KEY (Role_m0) REFERENCES STORMAG; 
